src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from .views import HomeView, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "posts"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='detail'),
    path('<str:slug>/edit/', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/delete/', BlogPostDelete.as_view(), name='delete'),
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False)
    content = models.TextField(blank=True)
    image = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on', 'title']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def author_or_not(self):
        if self.author:
            return self.author.username
        return 'l\'auteur inconnu'

    def get_absolute_url(self):
        return reverse('posts:home')

src/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import BlogPost


class HomeView(ListView):
    model = BlogPost
    context_object_name = 'posts'
    template_name = 'posts/home.html'


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/posts_create.html'
    fields = ['title', 'content']


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/posts_edit.html'
    fields = ['title', 'content', 'author', 'created_on', 'published']


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'


class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = 'posts/post_delete.html'
    success_url = reverse_lazy('posts:home')
    context_object_name = 'post'

src/posts/templates/posts/home.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

    {% for post in posts %}
        <div class="blog">
            <div class="red">{{ post.title }}</div>

            {% if request.user.is_authenticated %}
            <div>
                <a href="{% url 'posts:edit' post.slug %}">modifier</a> - <a href="{% url 'posts:delete' post.slug %}">supprimer</a>
            </div>
            {% endif %}

            <p>Publié(e) par <i>{{ post.author_or_not }}</i> le {{ post.created_on|date:'j F Y' }}</p>
            <p>{{ post.content|safe|truncatewords:50 }}</p>
            <button><a href="{% url 'posts:detail' post.slug %}">Lire</a></button>
        </div>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </div>

{% endblock %}

src/posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block title %} supprimer un article {% endblock %}

{% block content %}

    <h1>supprimer cet article</h1>

    <form method="POST">

        {% csrf_token %}

        <p>Voulez-vous supprimer l'article '{{ post.title }}'</p>
        <input type="submit" value="Supprimer">

    </form>

{% endblock %}

src/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} {{ post.slug }} {% endblock %}

{% block content %}


    <h1>{{ post.title }}</h1>
    <p>Dernière modification : {{ post.last_updated }}</p>
    <img src="{{ post.image.url }}" alt="image article">
    <p>{{ post.content|safe|linebreaks }}</p>
    <i>Rédigé(e) par {{ post.author_or_not }} le {{ post.created_on|date:'j F Y'}}</i>

{% endblock %}

src/posts/templates/posts/posts_create.html
{% extends 'base.html' %}

{% block title %} créer un article {% endblock %}

{% block content %}

    <h1>créer l'article</h1>

    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Créer">

    </form>

{% endblock %}

src/posts/templates/posts/posts_edit.html
{% extends 'base.html' %}

{% block title %} modifier l'article {% endblock %}

{% block content %}

    <h1>modifier l'article</h1>

    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Modifier">

    </form>

{% endblock %}

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

    <div class="skull">Site de mon Blog</div>

    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Créer article</a>
        {% endif %}
    </nav>

    {% block content %}{% endblock %}

</body>
</html>